config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'about', to: "pages#about"
  resources :articles
  resources :categories
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 14 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                       uniqueness: { case_sensitive: false }, 
                       length: { minimum: 4, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You are not authorized"
      redirect_to signin_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit    
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can't perfotm actions with this article"
      redirect_to @article
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, except: [:create, :new, :index ]
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Succesfully created a new category"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category name succesfully updated"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "Category successfully deleted"
    redirect_to categories_path
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private 

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "Something wrong with your details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end


  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Account info was updated successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account successfully deleted"
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can't perform these actions"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-6 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header fst-italic">
        by <%= link_to article.user.username, user_path(article.user) %>
        </div>
        <% if article.categories.any? %>
            <div class="mt-2">
              <%= render article.categories %>
            </div>
          <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "link-success" %></h5>
          <div class="card-text"><%= simple_format(truncate(article.description, length: 100)) %>
          </div>
            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
              <%= link_to "View", article_path(article), class: "btn btn-success"%>
              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-warning" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            </div>
        </div>
        <div class="card-footer text-muted">
          <small> Created <%= time_ago_in_words(article.created_at) %> ago,
          edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/error_messages', obj: @article %>
      <%= form_with(model: @article, class: "shadow mb-5 p-3 bg-info rounded",local: true) do |f| %>
        
        <%= f.label :title, class: "fw-bold col-2 col-form-label" %>
        <div class="col-12">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
        </div>
        
        <%= f.label :description, class: "fw-bold col-2 col-form-label" %>
        <div class="col-12">
          <%= f.text_area :description, rows: 7, class: "form-control shadow rounded", placeholder: "Description of article" %>
        </div>

        <%= f.label :category, "Category list (can be empty)", class: "fw-bold col-4 col-form-label" %>
        <div class="col-12">
          <%= f.collection_select(:category_ids, Category.all,:id, :name, { prompt: "Select categories from the list below" }, { multiple: true, class: "form-select shadow rounded" }) %>
        </div>

        <div class="mb-3 text-center">
          <%= f.submit class: "btn btn-outline-dark btn-lg mt-4 ml-10" %>
        </div>

        <div class="text-center">
          <%= link_to '[ Return ]', articles_path, class: "text-center text-dark" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;">Edit article</h1>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<h1 class="text-center" style="position: relative; top: 30px; margin-bottom: 60px;">Articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="text-center flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<div class="container">
<h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;">Create a new article</h1>
<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<h2 class="text-center" style="position: relative; top: 30px; margin-bottom: 30px;"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-12 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header fst-italic">
          by <%= link_to @article.user.username, user_path(@article.user) %>
          <div class="mt-2">
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          </div>
          <% if @article.categories.any? %>
            <div class="mt-2">
              <%= render @article.categories %>
            </div>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to @article.title, article_path(@article), class: "link-success" %></h5>
          <div class="card-text"><%= simple_format(truncate(@article.description, length: 100)) %>
          </div>
            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
              <%= link_to "View", article_path(@article), class: "btn btn-success"%>
              <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-warning" %>
              <%= link_to "Delete", article_path(@article), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            </div>
        </div>
        <div class="card-footer text-muted">
          <small> Created <%= time_ago_in_words(@article.created_at) %> ago,
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-dark ms-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/error_messages', obj: @category %>
<%= form_with(model: @category, class: "shadow mb-5 p-3 bg-info rounded",local: true) do |f| %>

  <div class="mb-3">
    <%= f.label :name, "Category name", class: "fw-bold col-2 col-form-label" %>
    <div class="col-12">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter category name" %>
    </div>
  </div>

  <div class="mb-3 text-center">
    <%= f.submit class: "btn btn-outline-dark btn-lg mt-4 ml-10" %>
  </div>

  <div class="text-center">
    <% if @category.name %>
      <%= link_to '[ Return ]', category_path(@category), class: "text-center text-dark" %>
    <% else %>
      <%= link_to '[ Return ]', categories_path, class: "text-center text-dark" %>
    <% end%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;">Edit category name</h1>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <h1 class="text-center my-4">Categories</h1>

  <div class="flickr_pagination">
      <%= will_paginate @categories, :container => false %>
  </div>

  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-5 mt-4">
        <div class="card text-center shadow mb-3 bg-body rounded">
          <div class="card-body">
            <h5 class="card-title mb-2">
              <%= link_to category.name, category_path(category), class: "link-success" %>
            </h5>
            <div class="card-text">
              <%= pluralize(category.articles.count, "artcile") %>
            </div>
            <% if logged_in? &&current_user.admin? %>
              <%= link_to "Delete", category_path(category), method: :delete, data: { confirm: "Are you sure to delete this category?" }, class: "btn btn-danger mt-2" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(category.created_at) %> ago,
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>

</div>

app/views/categories/new.html.erb
<div class="container">
  <h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;">Create a new category</h1>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10">
        <%= render 'shared/error_messages', obj: @category %>
        <%= form_with(model: @category, class: "shadow mb-5 p-3 bg-info rounded",local: true) do |f| %>

          <div class="mb-3">
            <%= f.label :name, "Category name", class: "fw-bold col-2 col-form-label" %>
            <div class="col-12">
              <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter category name" %>
            </div>
          </div>

          <div class="mb-3 text-center">
            <%= f.submit class: "btn btn-outline-dark btn-lg mt-4 ml-10" %>
          </div>

          <div class="text-center">
            <%= link_to '[ Return ]', root_path, class: "text-center text-dark" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/categories/show.html.erb
<div class="container">
  <h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;">Category: <%= @category.name %></h1>
</div>

<div class="text-center mt-3">
  <% if logged_in? && current_user.admin? %>
  <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-warning" %>
  <% end %>
</div>

<h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;">Articles</h1>

  <div class="flickr_pagination">
      <%= will_paginate @articles, container: false %>
  </div>

<%= render 'articles/article'%>

  <div class="flickr_pagination">
      <%= will_paginate @articles, container: false %>
  </div>

</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <small>Copyright &copy; <%= link_to "Tim Frolov", "https://vk.com/dragneell9"%></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg|%>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show " role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo-text" %>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Our users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "View articles", articles_path, class: "dropdown-item" %>
            </li>
            <li><%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "View categories", categories_path, class: "dropdown-item" %>
            </li>
            <% if (logged_in? && current_user.admin?) %>
            <li><%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
            </li>
            <% end %>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <%= "(Admin)" if current_user.admin? %>Profile [<%= current_user.username %>]
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Your profile", user_path(current_user), class: "dropdown-item" %>
            </li>
            <li><%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
            </li>
            <li><%= link_to "Delete account", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" }%>
            </li>
          </ul>
        </li>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", signin_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
        />
        <button class="btn btn-outline-success" type="submit">
          Search
        </button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/navbar'%>
      <div class="main">
        <%= render 'layouts/messages'%>
        <%= yield %>
      </div>
      <div class="footer">
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<ul>
  <li>Created by Tim Frolov</li>
</ul>

<%= link_to 'Articles list', articles_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-light rounded">
    <h1 class="display-4 fw-bolder">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/error_messages', obj: @user %>
      <%= form_with(model: @user, class: "shadow mb-5 p-3 bg-info rounded",local: true) do |f| %>

        <div class="mb-3">
          <%= f.label :username, class: "fw-bold col-2 col-form-label" %>
          <div class="col-12">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter username" %>
          </div>
        </div>

        <div>
          <%= f.label :email, class: "fw-bold col-2 col-form-label" %>
          <div class="col-12">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter email address" %>
          </div>
        </div>

         <div>
          <%= f.label :password, class: "fw-bold col-2 col-form-label" %>
          <div class="col-12">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter password" %>
          </div>
        </div>

        <div class="mb-3 text-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account info", class: "btn btn-outline-dark btn-lg mt-4 ml-10") %>
        </div>

        <div class="text-center">
          <%= link_to '[ Return ]', root_path, class: "text-center text-dark" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
<h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;">Edit your profile</h1>
<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1 class="text-center" style="margin-top: 20px; margin-bottom: 20px;">Our Bloggers</h1>

  <div class="flickr_pagination">
      <%= will_paginate @users, :container => false %>
  </div>

  <div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-header fst-italic">
          <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to gravatar_for(user, size: 120), user %></h5>
            <div class="card-text"><%= pluralize(user.articles.count, "article") %>
            </div>
            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
              <%= link_to "View profile", user, class: "btn btn-success"%>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit", edit_user_path(user), class: "btn btn-warning" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete account", user_path(user), method: :delete, data: { confirm: "Are you sure to delete this account?" }, class: "btn btn-danger" %>
              <% end %>
            <% end %>
            </div>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  
    <div class="flickr_pagination">
      <%= will_paginate @users, :container => false %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
<h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;">Sign up for Alpha Blog</h1>
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
<h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;"><%= @user.username %> profile</h1>
<%= gravatar_for @user, size: 150 %>

<div class="text-center mt-3">
  <% if logged_in? && @user == current_user %>
  <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-warning" %>
  <% end %>
</div>

<h1 class="text-center" style="position: relative; top: 20px; margin-bottom: 40px;">Articles</h1>

  <div class="flickr_pagination">
      <%= will_paginate @articles, :container => false %>
  </div>

<%= render 'articles/article'%>

  <div class="flickr_pagination">
      <%= will_paginate @articles, :container => false %>
  </div>

</div>